### ISSUE TITLE
"Panic" errors are causing web component statefulness to reset

### ISSUE THREAD

**Issue by jpeg07** [lurk-lang/lurk-web-utils#7]
Currently, state is retained across multiple instances of the web component on a single page. Commitments stored in one block and can be opened in later blocks, etc.

However, if a command is run that causes the lurk-rs code to panic, the statefulness resets and any stored commitments, e.g., are lost and future attempts to open them will fail. We need (I think) to catch these panics in rust so they are returned to the component in a way that does not cause loss of state. 

@samuelburnham is this something you can work on in coordination with @jlogelin? I think you're knowledge of Lurk and Rust are going to make you the best person for the job.

**Comment by porcuquine** [comment]
I think the short-term solution is to catch panics which occur during evaluation.
